# Name of your application. Used to uniquely configure containers.
service: my-sample-app

# Name of the container image.
image: ghcr.io/gurpreetArtesian/my-sample-app:latest

# Required for use of ASP.NET Core with Kamal-Proxy.
env:
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: true

# Deploy to these servers.
servers:
  web:
    - 172.30.252.9  # Deployment server IP from GitHub Secrets

# Enable SSL auto certification via Let's Encrypt (for production usage).
proxy:
  ssl: false  # Set to true if using a domain with HTTPS
  host: 172.30.252.9  # Public or local domain name
  app_port: 8080  # Change if your app runs on a different port

# Credentials for your image host.
registry:
  server: ghcr.io
  username: <%= ENV['KAMAL_REGISTRY_USERNAME'] %>
  password: <%= ENV['KAMAL_REGISTRY_PASSWORD'] %>

# Configure builder setup.
builder:
  arch: amd64  # Keeping this as per the template

# Volume mounting for persistence.
volumes:
  - "/opt/docker/my-sample-app/App_Data:/app/App_Data"
