# Name of your application. Used to uniquely configure containers.
service: my-sample-app

# Name of the container image.
image: ghcr.io/${{ secrets.KAMAL_REGISTRY_USERNAME }}/my-sample-app:latest

# Required for use of ASP.NET Core with Kamal-Proxy.
env:
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: true

# Deploy to these servers.
servers:
  web:
    - "${{ secrets.KAMAL_DEPLOY_IP }}"  # Deployment server IP from GitHub Secrets

# Enable SSL auto certification via Let's Encrypt (for production usage).
proxy:
  ssl: false  # Set to true if using a domain with HTTPS
  host: ${{ secrets.KAMAL_DEPLOY_IP }}  # Public or local domain name
  app_port: 8080  # Change if your app runs on a different port

# Credentials for your image host.
registry:
  server: ghcr.io
  username: "${{ secrets.KAMAL_REGISTRY_USERNAME }}"
  password: "${{ secrets.GH_TOKEN }}"

# Configure builder setup.
builder:
  arch: amd64  # Keeping this as per the template

# Volume mounting for persistence.
volumes:
  - "/opt/docker/my-sample-app/App_Data:/app/App_Data"
