name: Release
permissions:
  packages: write
  contents: write
on:
  workflow_run:
    workflows: ["Build Container"]
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  KAMAL_REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}
  KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
  KAMAL_DEPLOY_IP: ${{ secrets.KAMAL_DEPLOY_IP }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: my-local-wsl
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.KAMAL_REGISTRY_USERNAME }}
          password: ${{ env.KAMAL_REGISTRY_PASSWORD }}

      - name: Setup SSH Key with Passphrase
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY_PASSPHRASE }}" > ~/.ssh/passphrase.txt
          chmod 600 ~/.ssh/passphrase.txt
          
          eval "$(ssh-agent -s)"
          SSH_ASKPASS=/bin/cat ssh-add ~/.ssh/id_rsa < ~/.ssh/passphrase.txt

          # Optional: Verify SSH connection
          ssh -o StrictHostKeyChecking=no gurpreet@${{ secrets.KAMAL_DEPLOY_IP }} "echo 'SSH Connection Successful'"

      - name: Setup Ruby & Install Kamal
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - run: gem install kamal

      - name: Kamal Deploy
        run: |
          kamal deploy --verbose
