name: Release
permissions:
  packages: write
  contents: write
on:
  workflow_run:
    workflows: ["Build Container"] # Ensure this matches the actual name
    types:
      - completed # Runs when "Build Container" finishes successfully
  workflow_dispatch: # Allows manual trigger

env:
  DOCKER_BUILDKIT: 1
  KAMAL_REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}
  KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
  KAMAL_DEPLOY_IP: ${{ secrets.KAMAL_DEPLOY_IP }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: my-local-wsl
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.KAMAL_REGISTRY_USERNAME }}
          password: ${{ env.KAMAL_REGISTRY_PASSWORD }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Connection
        run: |
          ssh -i ~/.ssh/github_actions -o StrictHostKeyChecking=no user@${{ secrets.KAMAL_DEPLOY_IP }} "echo 'SSH Connection Successful'"

      - name: Test Docker Login
        run: |
          echo "${{ secrets.KAMAL_REGISTRY_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.KAMAL_REGISTRY_USERNAME }} --password-stdin

      - name: Setup Ruby & Install Kamal
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - run: gem install kamal

      - name: Kamal Deploy
        run: |
          kamal deploy --verbose
