name: Test Secrets
permissions:
  packages: write
  contents: read
on:
  workflow_dispatch:  # Only runs when triggered manually
  

env:
  DOCKER_BUILDKIT: 1
  environment: my-local-wsl
  KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}  # Set this in GitHub Secrets
  KAMAL_REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}  # Use a Personal Access Token (PAT)

jobs:
  build:
    runs-on: ubuntu-latest
    environment: my-local-wsl  # Add this to access secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          environment: my-local-wsl
          username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          password: ${{ env.KAMAL_REGISTRY_PASSWORD }}

      - name: Check if login was successful
        run: docker info
